after-login-command = []

after-startup-command = [ 
                          'exec-and-forget sketchybar',
                          'exec-and-forget borders active_color=0xffb4b5b6 inactive_color=0xff494d64 width=5.0'
                        ]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        30
outer.right =      5

[mode.main.binding]
ctrl-cmd-1 = 'close'
ctrl-cmd-2 = 'layout tiles horizontal'
ctrl-cmd-3 = 'layout tiles vertical'
ctrl-cmd-4 = 'layout accordion horizontal vertical'

# change focus
alt-q = 'focus left'
alt-w = 'focus down'
alt-e = 'focus up'
alt-r = 'focus right'

ctrl-cmd-left = 'focus left'
ctrl-cmd-down = 'focus down'
ctrl-cmd-up = 'focus up'
ctrl-cmd-right = 'focus right'

# move windows
alt-a = 'move left'
alt-s = 'move down'
alt-d = 'move up'
alt-f = 'move right'

ctrl-cmd-shift-left = 'move left'
ctrl-cmd-shift-down = 'move down'
ctrl-cmd-shift-up = 'move up'
ctrl-cmd-shift-right = 'move right'

# resize
ctrl-cmd-z = 'resize smart -80'
ctrl-cmd-x = 'resize smart +80'
alt-z = 'resize smart -80'
alt-x = 'resize smart +80'

# workspaces
ctrl-cmd-q = 'workspace 0'
ctrl-cmd-w = 'workspace 1'
ctrl-cmd-e = 'workspace 2'
ctrl-cmd-r = 'workspace 3'
ctrl-cmd-t = 'workspace 4'
ctrl-cmd-a = 'workspace 5'
ctrl-cmd-s = 'workspace 6'
ctrl-cmd-d = 'workspace 7'
ctrl-cmd-f = 'workspace 8'
ctrl-cmd-g = 'workspace 9'

# move workspace
ctrl-cmd-shift-q = 'move-node-to-workspace 0'
ctrl-cmd-shift-w = 'move-node-to-workspace 1'
ctrl-cmd-shift-e = 'move-node-to-workspace 2'
ctrl-cmd-shift-r = 'move-node-to-workspace 3'
ctrl-cmd-shift-t = 'move-node-to-workspace 4'
ctrl-cmd-shift-a = 'move-node-to-workspace 5'
ctrl-cmd-shift-s = 'move-node-to-workspace 6'
ctrl-cmd-shift-d = 'move-node-to-workspace 7'
ctrl-cmd-shift-f = 'move-node-to-workspace 8'
ctrl-cmd-shift-g = 'move-node-to-workspace 9'

# open terminal
ctrl-cmd-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# alt-tab
ctrl-cmd-tab = 'workspace-back-and-forth'
ctrl-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# fullscreen
ctrl-cmd-v  = 'fullscreen'
ctrl-cmd-shift-v = 'layout floating tiling'
#ctrl-cmd-shift-v = 'macos-native-fullscreen'

# service mode
ctrl-cmd-c = 'mode service'

# service bindings
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
#backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

a = ['join-with left', 'mode main']
s = ['join-with down', 'mode main']
d = ['join-with up', 'mode main']
f = ['join-with right', 'mode main']


[workspace-to-monitor-force-assignment]
    0 = 'main'
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'secondary'
    6 = 'secondary'
    7 = 'secondary'
    8 = 'secondary'
    9 = 'secondary'

# windows that should float
[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

## move to roon to workspace
# check with: -->  aerospace list-windows --monitor all --format %{app-bundle-id}

# W (VSCode)
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 1']

# E (Remote)
[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = ['move-node-to-workspace 2']

#[[on-window-detected]]
#if.app-id = 'tv.jellyfin.player'
#run = ['move-node-to-workspace 2']

# R (SmartGit)
[[on-window-detected]]
if.app-id = 'com.syntevo.smartgit'
run = ['move-node-to-workspace 3']

# T (KeePassXC)
[[on-window-detected]]
if.app-id = 'org.keepassxc.keepassxc'
run = ['move-node-to-workspace 4']

# D (Obsidian)
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['move-node-to-workspace 7']

# F (Roon)
[[on-window-detected]]
if.app-id = 'com.roon.Roon'
run = ['move-node-to-workspace 8']

# G (Discord)
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['move-node-to-workspace 9']






# com.fredrikburmester.streamyfin